### ISSUE TITLE
How about restores?

### ISSUE THREAD

**Issue by andreapavoni** [rex79/pgbackups#2]
Hi Roberto! how's going? :-)

I'm very interested in your scripts to backup PG, I did some tests on my machines and it works flawlessy. The scripts are pretty easy to understand, however, I'm a bit worried about restores with the N files it generates for each backup.

Do you plan to release some script to restore them?

What is the supposed way to do a full restore of a PG backup (schemas, data, extensions...)? I could help in writing the restore script ;-)

Thanks in advance, keep up with the good work! ;-)

**Comment by rex79** [comment]
Hi Andrea! I'm fine thanks and you?

Thanks for using my scripts I'm glad that you find it useful.
Right now I've not thinking about an automatic restore but it could be usefull. The backup that I made could be easily restore with postgres cli.

If you want to write the restore script you are welcome!

**Comment by andreapavoni** [comment]
Thanks, I'm going to try this and I'll let you know if/when is ready.

Closing this issue, I'll eventually open a PR in the future :-)

thanks again!
